In [ ]:
!pip install pandas numpy matplotlib seaborn scikit-learn

In [8]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.metrics import mean_squared_error, classification_report
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor

import warnings
warnings.filterwarnings("ignore")

In [10]:
df = pd.read_csv("Hospital_Inpatient_Discharges__SPARCS_De-Identified___2021_20231012.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2101588 entries, 0 to 2101587
Data columns (total 33 columns):
 #   Column                               Dtype
---  ------                               -----
 0   Hospital Service Area                object
 1   Hospital County                      object
 2   Operating Certificate Number         float64
 3   Permanent Facility Id                float64
 4   Facility Name                        object
 5   Age Group                            object
 6   Zip Code - 3 digits                  object
 7   Gender                               object
 8   Race                                 object
 9   Ethnicity                            object
 10  Length of Stay                       object
 11  Type of Admission                    object
 12  Patient Disposition                  object
 13  Discharge Year                       int64
 14  CCSR Diagnosis Code                  object
 15  CCSR Diagnosis Description           object
 16  CCSR Procedure Code                  object
 17  CCSR Procedure Description           object
 18  APR DRG Code                         int64
 19  APR DRG Description                  object
 20  APR MDC Code                         int64
 21  APR MDC Description                  object
 22  APR Severity of Illness Code         int64
 23  APR Severity of Illness Description  object
 24  APR Risk of Mortality                object
 25  APR Medical Surgical Description     object
 26  Payment Typology 1                   object
 27  Payment Typology 2                   object
 28  Payment Typology 3                   object
 29  Birth Weight                         object
 30  Emergency Department Indicator       object
 31  Total Charges                        object
 32  Total Costs                          object
dtypes: float64(2), int64(4), object(27)
memory usage: 529.1+ MB

In [15]:
df.describe()

       Operating Certificate Number  ...  APR Severity of Illness Code
count                  2.089497e+06  ...                  2.101588e+06
mean                   4.990270e+06  ...                  2.122646e+00
std                    2.234939e+06  ...                  9.556966e-01
min                    1.010000e+05  ...                  0.000000e+00
25%                    2.951001e+06  ...                  1.000000e+00
50%                    5.902001e+06  ...                  2.000000e+00
75%                    7.002020e+06  ...                  3.000000e+00
max                    7.004010e+06  ...                  4.000000e+00

[8 rows x 6 columns]

In [19]:
df["Length of Stay"]= df ["Length of Stay"].replace("120 +",120)
df["Length of Stay"]= pd.to_numeric(df["Length of Stay"])
df.isna().sum()

Hospital Service Area                    10642
Hospital County                          10642
Operating Certificate Number             12091
Permanent Facility Id                    10642
Facility Name                                0
Age Group                                    0
Zip Code - 3 digits                      45062
Gender                                       0
Race                                         0
Ethnicity                                    0
Length of Stay                               0
Type of Admission                            0
Patient Disposition                          0
Discharge Year                               0
CCSR Diagnosis Code                       1634
CCSR Diagnosis Description                1634
CCSR Procedure Code                     576021
CCSR Procedure Description              576021
APR DRG Code                                 0
APR DRG Description                          0
APR MDC Code                                 0
APR MDC Description                          0
APR Severity of Illness Code                 0
APR Severity of Illness Description       2550
APR Risk of Mortality                     2550
APR Medical Surgical Description             0
Payment Typology 1                           0
Payment Typology 2                     1072245
Payment Typology 3                     1768881
Birth Weight                           1894731
Emergency Department Indicator               0
Total Charges                                0
Total Costs                                  0
dtype: int64

In [20]:
for column in df.columns:
    unique_values = len(df[column].unique())
    print(f"Number of unique values in {column}:{unique_values}")

Number of unique values in Hospital Service Area:9
Number of unique values in Hospital County:58
Number of unique values in Operating Certificate Number:169
Number of unique values in Permanent Facility Id:206
Number of unique values in Facility Name:205
Number of unique values in Age Group:5
Number of unique values in Zip Code - 3 digits:51
Number of unique values in Gender:3
Number of unique values in Race:4
Number of unique values in Ethnicity:4
Number of unique values in Length of Stay:194
Number of unique values in Type of Admission:6
Number of unique values in Patient Disposition:19
Number of unique values in Discharge Year:1
Number of unique values in CCSR Diagnosis Code:478
Number of unique values in CCSR Diagnosis Description:478
Number of unique values in CCSR Procedure Code:321
Number of unique values in CCSR Procedure Description:321
Number of unique values in APR DRG Code:334
Number of unique values in APR DRG Description:334
Number of unique values in APR MDC Code:26
Number of unique values in APR MDC Description:26
Number of unique values in APR Severity of Illness Code:5
Number of unique values in APR Severity of Illness Description:5
Number of unique values in APR Risk of Mortality:5
Number of unique values in APR Medical Surgical Description:3
Number of unique values in Payment Typology 1:9
Number of unique values in Payment Typology 2:10
Number of unique values in Payment Typology 3:10
Number of unique values in Birth Weight:131
Number of unique values in Emergency Department Indicator:2
Number of unique values in Total Charges:1818969
Number of unique values in Total Costs:1549652

In [ ]:
df = df[df["Patient Disposition"]!= "Expired"]

In [ ]:
#EDA 
sns.boxplot(x="Payment Typology 1", y="Length of Stay", data=df)
plt.title("Payment Typology 1 vs Length of Stay")